### PR TITLE
Unsafe Cross-Origin Links #4961

### PR DESCRIPTION
**Pull request by badijm**
Tested w/ **Lighthouse**. 

#4961  
 
after
before

### CODE REVIEW

**Comment by joekrauss** [comment]
Max – I tested the changes on our local environment and we are seeing an issue with the links at the footer of theme. Any of the topic pages seem to reference a SeName?SeName=”VALUE”.

 



 


Joseph Krauss

**Comment by badijm** [comment]
hi, @joekrauss how can I reproduce this issue ?

**Comment by joekrauss** [comment]
Hello Max, I believe I responded to the wrong issue. My response and issue described above should be tied to the issue 4927 (#4959). After making the changes it creates URL links with SeName?SeName=”VALUE”. I'll copy this response on the correct issue. My apologies.

https://github.com/nopSolutions/nopCommerce/pull/4959

**Comment by badijm** [comment]
@joekrauss Oh, I gotcha. I'll take a look to another PR too. Thanks.

**Comment by DmitriyKulagin** [comment]
@badijm Thanks!

**Pull request merged**
