### PR TITLE
issues Fixes

### PR DESCRIPTION
**Pull request by hassanelsherbiny**
added the enhancement mentioned in the issue

### CODE REVIEW

**Comment by RomanovM** [comment]
@hassanelsherbiny  Thanks for your help. I recommend you make separate pull requests for every issue, no need to combine them.

**Comment by hassanelsherbiny** [comment]
@RomanovM actually when i push it auto append to the open pull request

**Comment by RomanovM** [comment]
@hassanelsherbiny Check your git client configuration or try to create a separate branch for an issue and then create a pr from such a branch.

**Comment by hassanelsherbiny** [comment]
ok, i will

**Pull request closed without merging**
