### PR TITLE
Update CheckoutController.cs

### PR DESCRIPTION
**Pull request by roberthej**
We need to save selected payment method before calculate Total of Cart

### CODE REVIEW

**Comment by roberthej** [comment]
We need to save selected payment method before calculate Total of Cart

**Comment by roberthej** [comment]
It will affect when the "_orderProcessingService.IsPaymentWorkflowRequiredAsync()" method calls the tax calculation "activeTaxProvider.GetTaxTotalAsync()" which is in the plugin "FixedOrByCountryStateZip" and cannot determine the additional fee which is retrieved using PaymentMethodSystemName, so it should be saved first.

**Comment by skoshelev** [comment]
Hi @roberthej. Okay, I understand what you mean. But I think that everything is just the opposite, you do not need to save this parameter before calling IsPaymentWorkflowRequiredAsync. More than that, we need to fix the IsPaymentWorkflowRequiredAsync method so that it calls the GetShoppingCartTotalAsync method with the parameter usePaymentMethodAdditionalFee = false. Since if payment is not required, then there is no need to take into account the additional fee for using the payment method

**Comment by roberthej** [comment]
Tnx @skoshelev

**Pull request closed without merging**
