### PR TITLE
Change to adminlte 3

### PR DESCRIPTION
**Pull request by Lymperis79**
It is the first time that i use git and sorry for the possible mistakes that i have done.... I just posted the changes that i have done till now.... for sure it need some more extra work and cleanup.... :D but this is a base for starting to continue.....
I am just posting it so you can check the first view of the changes
If you can give me tips so i can improve i will be happy 
Thanks

### CODE REVIEW

**Comment by Lymperis79** [comment]
It is the first time that i use git and sorry for the possible mistakes that i have done.... I just posted the changes that i have done till now.... for sure it need some more extra work and cleanup.... :D but this is a base for starting to continue.....  
Thanks

**Comment by Lymperis79** [comment]
I am adding and two screenshots  of the admin interface so you can have a view.

**Comment by ni-fara** [comment]
Hi @Lymperis79 ,does the changes you made support rtl. There is a [Official RTL Support](https://github.com/ColorlibHQ/AdminLTE/issues/2236) task at adminlte github.

**Comment by Lymperis79** [comment]
not yet i did not change the rtl file yet! I have not finished all the changes and for sure it possible to improve it more! One thing that i thought is to put an exta setting in the common setting and use one logo and the user to change the writen text in the top left title space! where in the pict is "Your store" text

**Comment by Lymperis79** [comment]
I added the rtl files. I have not checked everything but for start it does not look bad!

**Pull request closed without merging**
