### PR TITLE
Feature/order service tests

### PR DESCRIPTION
**Pull request by mstrYoda**
I had improved unit tests by adding tests for OrderService. I've also refactor some old linq2sql into linq expression.

### CODE REVIEW

**Comment by mstrYoda** [comment]
@skoshelev @RomanovM Hi guys, do you have any time to review this pr?

**Comment by skoshelev** [comment]
Hi @mstrYoda. Thank you for your help and interest in our project, unfortunately, we have not looked at your code yet. But we will do it in the near future.

**Comment by skoshelev** [comment]
Hi @mstrYoda. Thank you for your contribution, please do our suggestion and squash all commits to a single one. Also, this is only 16% percent of tests coverage OrderService class, we'll be grateful if you add more tests of this service

**Comment by skoshelev** [comment]
Implemented all suggested test in this https://github.com/nopSolutions/nopCommerce/commit/8885528e88c7bea07232236c128e94fb3c7ae80a commit

**Pull request closed without merging**
