### PR TITLE
Removed duplicated html containers from Product Reviews Page to preve…

### PR DESCRIPTION
**Pull request by poyker**
…nt css conflicts and potential SEO drawbacks

### CODE REVIEW

**Comment by poyker** [comment]
@DmitriyKulagin Yes there was something wrong. We corrected it and added the styling for the additional review ratings. Please let me know if all is good! 

Thank you!

**Comment by DmitriyKulagin** [comment]
>  If the user avatar display option is enabled, then the review text is shifted to the right

it still doesn't work

image

**Comment by poyker** [comment]
@DmitriyKulagin Thank you for pointing this out! I just pushed the Avatar fix changes. Hope this time all will be good :)

Thanks

**Comment by DmitriyKulagin** [comment]
@poyker  Everything is fine. Thanks a lot!

**Pull request merged**
