### PR TITLE
added vendor discount management code

### PR DESCRIPTION
**Pull request by hitinder**
Made code changes to allow vendors to view only their own discounts.
Administrator can view all discount types, and filter discounts based on vendor name.
Administrator can create new discount and assign vendor to it.

### CODE REVIEW

**Comment by AndreiMaz** [comment]
Hi,

So how is this property used (when assigned to a vendor)?

**Comment by saYRam** [comment]
Excuse me. Is the Vendor Discount implemented?

**Comment by RomanovM** [comment]
Related task https://github.com/nopSolutions/nopCommerce/issues/107

**Comment by RomanovM** [comment]
Thanks for your contribution. But right now we don't plan to implement it.

**Pull request closed without merging**
