### PR TITLE
Fix container path for app data

### PR DESCRIPTION
**Pull request by mitch-b**
When building the web application container, ensure it uses the proper path from documentation so that mounted paths work as expected.

See [forum post](https://www.nopcommerce.com/en/boards/topic/94314/docker-upgrade-installation-page#296108) by **giovannidebona**.

### CODE REVIEW

**Comment by skoshelev** [comment]
Hi @mitch-b. Thank you for your help. we'll update the docker image soon

**Comment by D3bo** [comment]
I updated with the new tag 4.50.2 that you just released, but seems that the version number is wrong:

image

**Comment by skoshelev** [comment]
hi @d3bo. I checked twice, all versions are set to 4.50.2

**Comment by mitch-b** [comment]
Thanks @D3bo and @skoshelev - the `4.50.2` tag is working as expected today.

**Pull request merged**
