### PR TITLE
Implemented Distributed inmemory caching with peers.

### PR DESCRIPTION
**Pull request by jspuij**
As the Redis cache implementation suffers from major network latency problems due to the single item fetches over the network and the implementation of RemoveWithPrefix as individual item synchronizations, (see https://github.com/nopSolutions/nopCommerce/issues/3875), I've implemented a new Distributed Inmemory Caching service that tackles these problems. Note that it does not require Redis or any backend cache server anymore as it simply synchronizes all memory caches.

It works by queuing all changes to the in memory cache array during a page request for distribution later. The queue is emptied at the end of the request to multiple clients that will distribute the changes to the other webservers on a configurable flush interval (default 30 seconds). This results in two netwerk calls per server pair per 30 seconds IF there is any cache information to sync. The network calls are a few kilobytes to 10ths of kilobytes and contain between 1 and some 1000s of cache messages and take only a few miliseconds to process.

The sync mechanism uses [DotNetty](https://github.com/Azure/DotNetty) to setup an async gzipped message pipeline over TCP that is fast and low latency. It completely bypasses the Http Pipeline.

The cache is smart enough to code "Clear" and "RemoveWithPrefix" into single messages and replay them on the other server. The cache also compares the entries on the target server based on a time stamp so it is important that all web servers are synchronized using NTP. 

I don't think it is wise to scale this beyond maybe 10 web frontends as it's push based so you'll end up with a lot of cache traffic when scaling to dozens of servers. I have not tested it with more than 3 nodes so YMMV.

Performance is roughly identical to the in memory cache. Remember that it can take up to 30 seconds (the sync interval) for changes in the cache to propagate to another server. This is not a problem in practice.

The scheduled tasks need some sort of locking mechanism to prevent multiple web frontends running the same task. The distributed cache cannot be used to synchronize the locks as it's only synchronized at fixed intervals. That is why this change includes a simple ILocker implementation using SQL Server.

Configuration is done in appSettings.json. The following settings are defined:

```json
     // Enable the distributed Memory Cache
    "DistributedCacheEnabled": true,

    // Peers to communicate with. May include your own IP.
    "DistributedCachePeers": "10.0.0.133,10.0.0.100",
    
     // Port to listen on for cache requests.
    "DistributedCachePort": 5432,

    // 30 second cache sync interval.
    "DistributedCacheSyncInterval": 30,

    // 60 second cache expiration cleanup interval.
    "DistributedExpirationScanInterval": 60,

    // Enable the Sql server locker
    "SqlLockerEnabled": true,
```

Configuration should be the same on all peers. I'd like some feedback from people running nopcommerce clusters whether this makes a difference and is a good addition to NopCommerce.

### CODE REVIEW

**Comment by AndreiMaz** [comment]
@skoshelev Also see https://github.com/nopSolutions/nopCommerce/issues/3875

**Comment by erkantdemir** [comment]
> As the Redis cache implementation suffers from major network latency problems due to the single item fetches over the network and the implementation of RemoveWithPrefix as individual item synchronizations, (see #3875), I've implemented a new Distributed Inmemory Caching service that tackles these problems. Note that it does not require Redis or any backend cache server anymore as it simply synchronizes all memory caches.
> 
> It works by queuing all changes to the in memory cache array during a page request for distribution later. The queue is emptied at the end of the request to multiple clients that will distribute the changes to the other webservers on a configurable flush interval (default 30 seconds). This results in two netwerk calls per server pair per 30 seconds IF there is any cache information to sync. The network calls are a few kilobytes to 10ths of kilobytes and contain between 1 and some 1000s of cache messages and take only a few miliseconds to process.
> 
> The sync mechanism uses [DotNetty](https://github.com/Azure/DotNetty) to setup an async gzipped message pipeline over TCP that is fast and low latency. It completely bypasses the Http Pipeline.
> 
> The cache is smart enough to code "Clear" and "RemoveWithPrefix" into single messages and replay them on the other server. The cache also compares the entries on the target server based on a time stamp so it is important that all web servers are synchronized using NTP.
> 
> I don't think it is wise to scale this beyond maybe 10 web frontends as it's push based so you'll end up with a lot of cache traffic when scaling to dozens of servers. I have not tested it with more than 3 nodes so YMMV.
> 
> Performance is roughly identical to the in memory cache. Remember that it can take up to 30 seconds (the sync interval) for changes in the cache to propagate to another server. This is not a problem in practice.
> 
> The scheduled tasks need some sort of locking mechanism to prevent multiple web frontends running the same task. The distributed cache cannot be used to synchronize the locks as it's only synchronized at fixed intervals. That is why this change includes a simple ILocker implementation using SQL Server.
> 
> Configuration is done in appSettings.json. The following settings are defined:
> 
> ```json
>      // Enable the distributed Memory Cache
>     "DistributedCacheEnabled": true,
> 
>     // Peers to communicate with. May include your own IP.
>     "DistributedCachePeers": "10.0.0.133,10.0.0.100",
>     
>      // Port to listen on for cache requests.
>     "DistributedCachePort": 5432,
> 
>     // 30 second cache sync interval.
>     "DistributedCacheSyncInterval": 30,
> 
>     // 60 second cache expiration cleanup interval.
>     "DistributedExpirationScanInterval": 60,
> 
>     // Enable the Sql server locker
>     "SqlLockerEnabled": true,
> ```
> 
> Configuration should be the same on all peers. I'd like some feedback from people running nopcommerce clusters whether this makes a difference and is a good addition to NopCommerce.

Hı,

I pulled your brach and I tried our servers. We have 3000 products and 2 languages. 
Distrubed cache throws this exception many times. Did you get this error?

`Got an error processing the cache entries at peer: 10.0.1.92:5432 Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'Castle.Proxies.CarouselProxy, DynamicProxyGenAssembly2'. Path '$values[20].Entry.Value.$values[0].$type', line 890, position 79. ---> System.IO.FileNotFoundException: Could not load file or assembly 'DynamicProxyGenAssembly2, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Reflection.Assembly.LoadWithPartialName(String partialName)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Nop.Services.Caching.CacheSynchronizationServerHandler.ChannelRead(IChannelHandlerContext context, Object message) in C:\agent\_work\4\s\Libraries\Nop.Services\Caching\CacheSynchronizationServerHandler.cs:line 45`

**Comment by jspuij** [comment]
We did not get that error. It seems that it tries (de)serializing an EF core entity that is proxied because of lazy loading. Depending on the code paths different objects end up in the cache, some of them not serializable. You'd have to track down which one it is yourself.

**Comment by jspuij** [comment]
I have rebased the changes onto the current Develop branch.

The cache, but rebased against master (4.20) can be found here:

https://github.com/BirdseyeviewNL/nopCommerce/tree/DistributedCacheMaster

**Comment by skoshelev** [comment]
Hi @jspuij Many thank you for your helping. 
We decided not to include these changes in the nopCommerce, as we have a plan to migrate to "Distributed caching from ASP.NET Core" (https://github.com/nopSolutions/nopCommerce/issues/4699) and for 4.30 we managed to solve the problem with the performance of Redis

**Comment by jspuij** [comment]
@skoshelev You must be kidding me. I'm getting weekly requests from people with 4.30 and clustered installs that want to use my cache because they have issues with performance. I'm not seeing any indication that you've solved the performance problems with redis. So I'm very eager to learn how you've solved them.

Hammering the cache with thousands of requests and also having the cache out of process so that the requests have to travel across process and network boundaries is what is causing this issue. It requires fundamental redesign of NopCommerce.

Could you explain and point to the commits that have alleviated the pressure on the Redis cache so that I can inform myself and possibly consider going back to "stock" nopcommerce?

**Comment by skoshelev** [comment]
Hi @jspuij. No, I'm not joking, at 4.30 we did a lot of work on reworking the caching system, replaced outdated libraries of working with radishes, added the ability to ignore timeout errors, and made a number of code optimizations. Before publishing the official release of the 4.30 version, we carried out load testing on the site using both the cache systems in memory and through Redis, the results were within the limits of equality (taking into account the delays at the transport layer and serialization). Nevertheless, we admit that the problem may persist on some systems, so we plan to implement support for "Distributed caching from ASP.NET Core"

**Comment by falvarez1** [comment]
@skoshelev you didn't answer the questions @jspuij posed.  The Dottnety cache synchronization solution seems to work well performance-wise, at least significantly better than the integrated Redis implementation.  I would also like to know what commits or PRs represent the rework to the cache system to fix the poor performance problems.

**Comment by jspuij** [comment]
This was the last email I got in response to this thread. It clearly indicates that 4.3 is still not good:

> I came across a thread on the nopcommerce forum where you built a
> distributed caching mechanism that was rejected by the nop team. We recently
> went through the upgrade from 4.0 to 4.3 with the promise that performance
> would be significantly better. What we are experiencing seems to be the same
> or worse. We were hoping you might be able to point us in the right
> direction to help solve or at least improve our situation. What we are
> trying to achieve is being able to handle 250-500 concurrent users if
> possible.
>
> We are running in azure app service against azure sql. No matter how much we
> juice up the app or database, we can't seem to scale well at all. We hit a
> wall pretty quickly with 20-40 users. We have cloudflare in front of it
> since we frequently get attacked and we needed a CDN. We have resorted to
> setting up web farms with 3 VMs running against the same azure sql database
> because the app always pegs the processor under sustained load and often
> crashes. Its costly to run so we spin it up when necessary. We originally
> tried redis after the upgrade so we could scale out, but quickly turned it
> off due to it doubling the request times. Now we are searching for anything
> that could help us squeeze more performance out of this application. You
> sound like you understand it quite well and I would be interested in talking
> with you about what has worked for you.
>
> - Jason

**Comment by untiedshoes** [comment]
> This was the last email I got in response to this thread. It clearly indicates that 4.3 is still not good:
> 
> > I came across a thread on the nopcommerce forum where you built a
> > distributed caching mechanism that was rejected by the nop team. We recently
> > went through the upgrade from 4.0 to 4.3 with the promise that performance
> > would be significantly better. What we are experiencing seems to be the same
> > or worse. We were hoping you might be able to point us in the right
> > direction to help solve or at least improve our situation. What we are
> > trying to achieve is being able to handle 250-500 concurrent users if
> > possible.
> > We are running in azure app service against azure sql. No matter how much we
> > juice up the app or database, we can't seem to scale well at all. We hit a
> > wall pretty quickly with 20-40 users. We have cloudflare in front of it
> > since we frequently get attacked and we needed a CDN. We have resorted to
> > setting up web farms with 3 VMs running against the same azure sql database
> > because the app always pegs the processor under sustained load and often
> > crashes. Its costly to run so we spin it up when necessary. We originally
> > tried redis after the upgrade so we could scale out, but quickly turned it
> > off due to it doubling the request times. Now we are searching for anything
> > that could help us squeeze more performance out of this application. You
> > sound like you understand it quite well and I would be interested in talking
> > with you about what has worked for you.
> > 
> > * Jason
https://github.com/nopSolutions/nopCommerce/issues/5461#issuecomment-785863815

**Pull request closed without merging**
