### PR TITLE
Feature-3659 enable guest edit delete on checkout  

### PR DESCRIPTION
**Pull request by hfz-r**

### CODE REVIEW

**Comment by hfz-r** [comment]
**OPC**

opc

- buttons "Edit" and "Delete" looked crowded. Any suggestion to where to put it?

**Comment by hfz-r** [comment]
**MSC**

msc

**Comment by DmitriyKulagin** [comment]
Joined with #3659

**Comment by DmitriyKulagin** [comment]
@hfz-r Thanks for your contribution to development.

**Pull request merged**
