### PR TITLE
Fix: Hide the "register" link in the header when registration is disabled #4540

### PR DESCRIPTION
**Pull request by badijm**
https://github.com/nopSolutions/nopCommerce/issues/4540

### CODE REVIEW

**Comment by Lymperis79** [comment]
In case the registration is disabled in the login.cshtml left block there is a text that registration is not allowed! I think that this is not required and it should be only the login part.

**Comment by badijm** [comment]
@Lymperis79 Sorry, I didn't quite get your point. Can you provide code example ?

**Comment by Lymperis79** [comment]
in this path \src\Presentation\Nop.Web\Views\Customer\Login.cshtml the lines 26 till 33 are giving the message that the registration is disabled. If there is no way to register it is unnecessary information :D

**Comment by badijm** [comment]
@Lymperis79 Got it. Thanks for that.

**Comment by Lymperis79** [comment]
I found one more part that has to be hidden when registration is disabled!
in this path \src\Presentation\Nop.Web\Views\Customer\Login.cshtml lines 41 till 51! they show a text and a button for registration! not necessary!

**Comment by badijm** [comment]
@Lymperis79 Alright. Pushed new changes.

**Comment by badijm** [comment]
Hi, @Lymperis79 any updates on it?

**Comment by holydk** [comment]
Closed #4978. Changes [here](https://github.com/nopSolutions/nopCommerce/commit/08574683f0795fdfe247cf3c55dd07183d738d20).

**Pull request closed without merging**
