### PR TITLE
 Feature 3536, Add recaptcha on forgot password page

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by skoshelev** [comment]
Hi @dborovsky  Thank you for your help. You forgot to add a validation check of the captcha in the controller, as for example, it’s done here https://github.com/nopSolutions/nopCommerce/blob/dbf0607192f920b84714998ceeb23e91ab4dd50e/src/Presentation/Nop.Web/Controllers/CustomerController.cs#L289, and you also forgot to add locales to upgrade.sql and defaultResources.nopres.xml files. But you do not need to make changes to the create_required_data.sql file, we will automatically generate it before release. Also pleace squash your commits in to one.

**Comment by dborovsky** [comment]
@sagar-patel-sls @skoshelev  I noted, i set instead _captchaSettings.ShowOnForgotPasswordPage, set _captchaSettings.ShowOnLoginPage.  I`ve fixed it with last commit. 

Now I hope verything fine

**Comment by skoshelev** [comment]
Thank you for your help. I merged your PR, but also I did some fixes in your code, you may see them on the develop branch

**Comment by dborovsky** [comment]
@skoshelev thank you. Maybe could you tell me, wich issue i can do next? What more important for you now?

**Comment by skoshelev** [comment]
Hi @dborovsky You can choose [any issue](https://github.com/nopSolutions/nopCommerce/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+4.20%22+no%3Aassignee) you are interested in for 4.20 but not assigned to anyone.

**Comment by pantonis** [comment]
> @dborovsky Thank you for your help. I merged your PR, but also I did some fixes in your code, you may see them on the develop branch

Can you tell how can I see final changes in order to manually add them to my shop which uses v.4.1

**Pull request closed without merging**
