### PR TITLE
Feature deco 138

### PR DESCRIPTION
**Pull request by rudgr**
Hi 

We need to be able to display the price of "customer enters" price products in the views.

tx

### CODE REVIEW

**Comment by AndreiMaz** [comment]
Hi Rutger,

1. What is https://dotcontrol.atlassian.net/browse/DECO-138 ?
2. What does it do (this pull request)?

**Comment by rudgr** [comment]
Ah sorry, that's an internal link.

We created this pull request because we need to display a price (minimum
price) in the product overview views for "customer enters price" products.
By default nopCommerce doesn't "hydrate" prices for "customer enters price"
products.


Op vr 30 dec. 2016 om 19:41 schreef Andrei Mazulnitsyn <
notifications@github.com>

**Comment by AndreiMaz** [comment]
Thanks! But unfortunately, it's not planned to be implemented out of the box

**Comment by rudgr** [comment]
I understand, could try ;-)

Op za 31 dec. 2016 om 18:31 schreef Andrei Mazulnitsyn <
notifications@github.com>

**Pull request closed without merging**
