### PR TITLE
Issue #1107 Avoid duplication when entering page sizes values

### PR DESCRIPTION
**Pull request by odises**
- **CategoryValidator** changed to avoid duplication in pageSizeOptions.
- **CategoryValidatorTests** added.

I don't have any idea which resources should be updated. all of them or just default one?

### CODE REVIEW

**Comment by AndreiMaz** [comment]
Thanks a lot! I would be great if you add the same validation to manufacturers (etc) as well

**Comment by odises** [comment]
Following validators changed to avoid duplication when entering page sizes values:

- **CategoryValidator**
- **ManufacturerValidator**
- **VendorValidator**
- **SettingValidator**

Also related unit tests implemented.

**Comment by AndreiMaz** [comment]
Thanks. Please also update \upgradescripts\3.70-the next version\upgrade.sql file (add locales to it as well)

**Comment by odises** [comment]
Your welcome. Ok.

**Comment by odises** [comment]
Done.

**Comment by odises** [comment]
Dear @AndreiMaz;
I made changes as you asked.

**Comment by AndreiMaz** [comment]
1. Thanks! Is it possible to create a new branch containing all changes in one commit? 
2. Please also drop PageSizeOptionsInAdvancedSettingsValidator. There's no need to validate it on the settings page. Hence you can also drop locales such as "Admin.Configuration.Settings.AllSettings.Fields.PageSizeOptions.IsInvalid"

**Pull request closed without merging**
