### PR TITLE
Added admin toggles for FirstName and LastName

### PR DESCRIPTION
**Pull request by rodolphito**
Make them like all other address entries. This allows a store owner to have optional names, or even disable name collection altogether to simplify GDPR compliance. Names are still collected with the Billing Address.

This is the implementation of issue #4064. It has been in use for over a month, and is working fine on my website.

Let me know if anything else needs doing to get this merged.

cc @RomanovM

### CODE REVIEW

**Comment by rodolphito** [comment]
Why did the build check fail? It builds successfully on my machine, how can I figure out what went wrong?

**Comment by RomanovM** [comment]
@rodolphito Thanks for your contribution. 
Builds are ok, but you should also change tests (see [here ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Tests/Nop.Web.MVC.Tests/Public/Validators/Customer/CustomerInfoValidatorTests.cs)and [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Tests/Nop.Web.MVC.Tests/Public/Validators/Customer/RegisterValidatorTests.cs)) accordingly, at now their checks are failed.

**Comment by DmitriyKulagin** [comment]
@rodolphito Hi
I checked your code, in general, everything is fine. We are waiting for corrections of tests and small adjustments for localization.
No values specified for the following locales:

- Admin.Configuration.Settings.CustomerUser.FirstNameEnabled
- Admin.Configuration.Settings.CustomerUser.FirstNameRequired
- Admin.Configuration.Settings.CustomerUser.LastNameEnabled
- Admin.Configuration.Settings.CustomerUser.LastNameRequired

**Comment by rodolphito** [comment]
I'll do that, thanks for reviewing.

**Comment by rodolphito** [comment]
Okay should be good to go now! Please advise if I missed anything. I look forward to my next contribution.

**Comment by DmitriyKulagin** [comment]
@rodolphito Thanks a lot!

**Pull request merged**
