### PR TITLE
Remove Microsoft.NETCore.App reference from Nop.Core.

### PR DESCRIPTION
**Pull request by MaxMommersteeg**
As by Microsoft's recommendation we should not explicitly reference `Microsoft.NETCore.App` or `NETStandard.Library` when targeting .NET Core or .NET Standard.

----

> When targeting .NET Core or .NET Standard, never have an explicit reference to the Microsoft.NETCore.App or NetStandard.Library metapackages via a <PackageReference> item in your project file.

[MSDN documentation](https://docs.microsoft.com/nl-nl/dotnet/core/tools/csproj#recommendations)

### CODE REVIEW

**Comment by MaxMommersteeg** [comment]
Was trying to add all individual packages earlier on but referencing `Microsoft.AspNetCore.All` makes this all a bit easier.

**Comment by Leftyx** [comment]
**Deprecate Microsoft.AspNetCore.All** is [deprecated](https://github.com/aspnet/AspNetCore/issues/3418).
And this is another [link](Microsoft.AspNetCore.App) helpful explanation.

**Comment by MaxMommersteeg** [comment]
Thanks, I did not realize that. Will see if I can correct the PR in a few hours if feasible.

**Comment by RomanovM** [comment]
We are a little late in accepting this pr, there is already .NET 5. 
Anyway, many thanks for your contribution.

**Pull request closed without merging**
