### PR TITLE
Upgrade to .Net Core 3.1

### PR DESCRIPTION
**Pull request by sefacan**
I've completed upgrading to version 3.1, but I noticed some problems with the plugin and widgets.
I haven't tested the url localization structure as well.
NopEditorTagHelper is no longer able to access TemplateBuilder. So I think I solved it with IHtmlHelper.
I replaced IRouteBuilder with IEndPointRouteBuilder.

It is not yet a finished work, but we can complete it together.

### CODE REVIEW

**Comment by sefacan** [comment]
Hi @AndreiMaz,
Did you review?

**Comment by jspuij** [comment]
@sefacan We have independently ported nopCommerce to version 3.1 as well, solved a few of your problems, but ran into a socket issue with 3.1 that makes it impossible to go further.

https://github.com/dotnet/runtime/issues/1218

https://github.com/BirdseyeviewNL/nopCommerce/tree/Update3.1

**Comment by Durkee** [comment]
> @sefacan We have independently ported nopCommerce to version 3.1 as well, solved a few of your problems, but ran into a socket issue with dotnet 3.1 that makes it impossible to go further.
> 
> [dotnet/runtime#1218](https://github.com/dotnet/runtime/issues/1218)
> 
> https://github.com/BirdseyeviewNL/nopCommerce/tree/Update3.1

The branch is not building.  You gave this branch to Microsoft to help you on your show stopper.

**Comment by jspuij** [comment]
@Durkee Are you sure our branch is not building?

This is the pull request of sefacan, not our branch. I just cloned it, switched to the Update3.1 branch and built it.

```Build succeeded.

C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Source\git\nopCommerce\src\Libraries\Nop.Core\Nop.Core.csproj]
C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Source\git\nopCommerce\src\Libraries\Nop.Core\Nop.Core.csproj]
Services\SquarePaymentManager.cs(269,51): warning CS0612: 'ITransactionsApi.RetrieveTransaction(string, string)' is obsolete [C:\Source\git\nopCommerce\src\Plugins\Nop.Plugin.Payments.Square\Nop.Plugin.Payments.Square.csproj]
Services\SquarePaymentManager.cs(323,50): warning CS0612: 'ITransactionsApi.CaptureTransaction(string, string)' is obsolete [C:\Source\git\nopCommerce\src\Plugins\Nop.Plugin.Payments.Square\Nop.Plugin.Payments.Square.csproj]
Services\SquarePaymentManager.cs(377,47): warning CS0612: 'ITransactionsApi.VoidTransaction(string, string)' is obsolete [C:\Source\git\nopCommerce\src\Plugins\Nop.Plugin.Payments.Square\Nop.Plugin.Payments.Square.csproj]
Services\SquarePaymentManager.cs(432,44): warning CS0612: 'ITransactionsApi.CreateRefund(string, string, CreateRefundRequest)' is obsolete [C:\Source\git\nopCommerce\src\Plugins\Nop.Plugin.Payments.Square\Nop.Plugin.Payments.Square.csproj]
    6 Warning(s)
    0 Error(s)
```

**Comment by sefacan** [comment]
@jspuij There is no valid error for the project not running. The problem is the socket problem in version 3.1.

**Comment by exileDev** [comment]
Thanks a lot for your contributions. We've already completed this task (see #3652) and it's available in the "develop" branch. Your pull request was also very helpful for us.

**Pull request closed without merging**
