### PR TITLE
Fix for issue 3424 - Set OrderGuid.

### PR DESCRIPTION
**Pull request by MaxMommersteeg**
Now setting `OrderGuid` at `PrepareOrderModel` method. This fixes issue https://github.com/nopSolutions/nopCommerce/issues/3424 that caused displayed `00000000-0000-0000-0000-000000000000` to be shown as `OrderGuid` (at `Admin/Order/Edit/{orderId}`) when:
* Modifying order status:
    1. Click `Change status`
    2. Click `Save`
    3. Click `Yes`

* Modifying order totals
    1. Click `Edit order totals`
    2. Click `Save order totals`
    3. Click `Yes`

___

`OrderModel.OrderGuid` is not set when entering the OrderController. Maybe that should have worked. I am not sure. Feedback is welcome.

### CODE REVIEW

**Comment by LubovKhokhlova** [comment]
Hello, MaxMommersteeg!
In the https://github.com/nopSolutions/nopCommerce/issues/3424 task, you also write about OrderStatus. It would be nice to fix them at the same time, as they break for one reason.

**Comment by MaxMommersteeg** [comment]
Hi,
That may be already fixed, not sure. I can verify that in a few hours and will update this PR if OrderStatus was not fixed yet.

**Comment by LubovKhokhlova** [comment]
Hello, MaxMommersteeg!
How are the things going with the implementation?

**Comment by LubovKhokhlova** [comment]
@MaxMommersteeg We fixed this issue https://github.com/nopSolutions/nopCommerce/commit/a6ad8c35803cc338ba5c5b93ad6002764f337231
Thank you for your help!

**Comment by MaxMommersteeg** [comment]
Sorry, was a bit busy lately. Glad you fixed the issue!

**Pull request closed without merging**
