### PR TITLE
#6723 fix for large forms causing 400 Bad Request

### LINKED ISSUE #6723: 400 bad request when trying to cancel/edit large order
nopCommerce version: 4.60.3

Steps to reproduce the problem: 

The order that I'm working with has 432 items.

When i try to cancel the order with the `cancel` button, or perform a manual status change, the change fails and the user receives a blank page. Dev tools and nop log show 400 bad request. 

Since the edit page is one big form that posts all input values regardless of what action is being taken on the order, and each order item has 6 attributes being posted, this results in 2,592 form fields being posted + approximately 25 other fields. So, the edit form for this order is submitting over 2,600 fields. This exceeds the default value of 1024 for the `RequestFormLimits` action attribute. I ran into a similar problem when developing a plugin for wholesale ordering.

The best fix, in my opinion would involve limiting the form fields to only submit the values to what is necessary for what is being changed.

The quick, less secure/robust fix would be adding `[DisableRequestSizeLimit]`, `[RequestFormLimits(ValueCountLimit = int.MaxValue, KeyLengthLimit = int.MaxValue)]` attributes to the `CancelOrder` action and other edit related actions which could suffer from this same issue.

I can certainly apply the attribute overrides to my local build to get it working, but I would like to see a more robust upstream fix for this.

### PR DESCRIPTION
**Pull request by danFbach**
This fixes #6723 and probably also related #5950.

As mentioned in #6723, I believe this should be reviewed for its potential for abuse - i.e., the submission of massive forms.

Also up for debate is the placement of the new code, although this seems to be the best place in my opinion.

### CODE REVIEW

**Comment by danFbach** [comment]
I have tried using a narrower approach, applying the attribute `[RequestFormLimits(ValueCountLimit = int.MaxValue)]` to both the OrderController as a whole, and to the CancelOrder action specifically.

When applied to the controller, the request appears to succeed and redirect to you the Edit page, but actually just executes the Edit action. It appears this fails because every sub-request (to components, widgets, etc) also exceeds the form limits, so presumably the FormValueRequired 'cancelorder' is lost...? 

When applied only to the CancelOrder action, you still receive the 400 bad request because when it is redirected to Edit action, the ValueCountLimit is exceeded for Edit action.

The *best* fix for this, would be to change this page so that you never submit so many form values, but require a rewrite of the views, actions and supporting js.

**Comment by skoshelev** [comment]
Hi @danFbach. Thank you for your help. We are also investigating solutions to this problem, at the moment our best option is to add the RequestFormLimits attribute to the BaseAdminController so as not to change the global setting. On the one hand, this should solve all such problems in the administration area, and on the other hand, it will not allow attacking the public part of the site. But we are still looking for a more flexible or configurable solution.

**Comment by danFbach** [comment]
@skoshelev I tried applying the RequestFormLimits attribute to the BaseAdminController and it had the same effect as when applied to the order controller. Something gets messed up with the routing and the FormValueRequired is missed - even though when I watch Request.Form while debugging, "cancelorder" is there.

**Comment by skoshelev** [comment]
Hi @danFbach. Yes, that's right, one attribute is not enough and I couldn't find the source of the problem. However, we found a solution that works, see [this commit](https://github.com/nopSolutions/nopCommerce/commit/a481be440a8505a01a0ae0f379fb2362782cf130). Thanks again for your help

**Pull request closed without merging**
