### PR TITLE
Download Service Test Added

### PR DESCRIPTION
**Pull request by Ayshkumar**

### CODE REVIEW

**Comment by apurvai007** [comment]
Can you please add description for this PR ?

**Comment by apurvai007** [comment]
I can see you have src/Tests/Nop.Tests/DownloadServiceTests.cs in the PR [#6996](https://github.com/nopSolutions/nopCommerce/pull/6996) as well, Is it intentional?

**Comment by Ayshkumar** [comment]
Both are same

**Comment by apurvai007** [comment]
> Both are same

Can you update your MRs to and remove redundancy/duplication ?

**Comment by Ayshkumar** [comment]
More unit tests #405
Added more TestCases for DownLoadService

**Comment by skoshelev** [comment]
We do not use mocks in our tests

**Pull request closed without merging**
