### PR TITLE
Fixed: Description of category and manufacturer images.

### PR DESCRIPTION
**Pull request by AltafKhatri**
#2254

### CODE REVIEW

**Comment by AltafKhatri** [comment]
#2250 fixed

**Comment by AltafKhatri** [comment]
#2250

**Comment by RomanovM** [comment]
Thanks for your contribution. We have already implemented it.

**Comment by RomanovM** [comment]
Related tasks https://github.com/nopSolutions/nopCommerce/issues/2250, https://github.com/nopSolutions/nopCommerce/issues/2254

**Pull request closed without merging**
