### PR TITLE
Update3.1 fixed

### PR DESCRIPTION
**Pull request by jspuij**
Updated to dotnet core 3.1.

Fixes:

https://github.com/nopSolutions/nopCommerce/issues/4259
https://github.com/nopSolutions/nopCommerce/pull/4235

Found the root cause for:

https://github.com/dotnet/runtime/issues/1218

IQueryables referencing a DBContext were put in the cache and on a next request reused from a different thread. This triggers a double dispose / free. Will create a repro for this for the .net core team.

For now I check in the memory cache whether the type that is going to be cached is the return value of a linq operator.

https://github.com/nopSolutions/nopCommerce/commit/30602faaeed42b4e4de2124c7caacc1026179e5b

https://github.com/nopSolutions/nopCommerce/commit/f1c77ec861f583a0cd2628904d1fdb8ae4647685

Rebased onto upstream develop for an easy merge.

### CODE REVIEW

**Comment by jspuij** [comment]
Please do not merge yet, there are some issues with DI in this branch. Manually reviewing the merges.

**Comment by jspuij** [comment]
So the DI is fixed. An earlier commit changed the container to the Microsoft.DependencyInjection.Abstraction container for a large part of the service registrations. I thought this was undesired. So I reverted these changes and followed the Autofac pattern for .NET core 3.0:

https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting

Note that the container cannot be built manually anymore but an AutofacProviderFactory has to be used, which makes the Startup class a little different (Register asp.net services first, then register Autofac services, then do application configuration.

**Comment by jspuij** [comment]
> 
> 
> why you delete this lines:
> engine.Resolve().Information("Application started");
> 
> ```
>         //install plugins
>         engine.Resolve<IPluginService>().InstallPlugins();
> ```

They are not deleted. They are moved to a method called StartEngine. This method is called after building of the request pipeline. This is done because Autofac containerbuilding with asp.net core 3+ is now controlled by asp.net core. So we cannot build the container ourselves anymore and the plugin installation needs a built container. So installation of the plugins is now done in the Configure method of the Startup class.

**Comment by mk148a** [comment]
> 
> 
> > why you delete this lines:
> > engine.Resolve().Information("Application started");
> > ```
> >         //install plugins
> >         engine.Resolve<IPluginService>().InstallPlugins();
> > ```
> 
> They are not deleted. They are moved to a method called StartEngine. This method is called after building of the request pipeline. This is done because Autofac containerbuilding with asp.net core 3+ is now controlled by asp.net core. So we cannot build the container ourselves anymore and the plugin installation needs a built container. So installation of the plugins is now done in the Configure method of the Startup class.

I was try to upgrade my website from netcore 2.2 but i cant success. I will share error log.

**Comment by exileDev** [comment]
Thanks a lot for your contributions. We've already completed this task (see #3652) and it's available in the "develop" branch. Your pull request was also very helpful for us.

**Comment by jspuij** [comment]
Thank you. Glad we could help. We will check the develop branch out.

**Pull request closed without merging**
