### PR TITLE
Allows you to make your own path base store. For example, domian.com/…

### PR DESCRIPTION
**Pull request by Alerinos**
Allows you to make your own path base store. 
For example ``domian.com/shop``

In the nginx configuration, just indicate:
```
location / {
```
at
```
location / shop {
```

Issue: https://github.com/nopSolutions/nopCommerce/issues/6847

### CODE REVIEW

**Comment by Alerinos** [comment]
In ``Admin/Log/List`` it is hardwired to generate a link to "See" when you click on the logs. This needs to be found and corrected.
image
Probably poorly constructed routing or ``/`` at the beginning.

**Comment by Alerinos** [comment]
I fixed all the "Edit" buttons, there are other elements that need to be improved. If I find something I will upload the changes.
I think I'm helping.

**Comment by Alerinos** [comment]
I fixed the tutorial with the inclusion of pathBase.
JS is problematic, I wanted to do nicer but couldn't do it

**Comment by RomanovM** [comment]
@Alerinos Thanks for this suggestion. I think this is related only to nginx configuration, so we'll leave it for customization.

**Comment by Alerinos** [comment]
@RomanovM I tried, but unfortunately it doesn't work because routing in ASP.net still returns 404. Also standard in HTML is to use base in the head. Every ASP.net template has a base.
I think you should include this PR or provide a guide on how to do it via nginx.

**Comment by Alerinos** [comment]
@RomanovM I still have not received the information, if it is possible I would like you to point me to the documentation.

According to Microsoft documentation, there must be PathBase as well as Base itself in Head. I have the impression that my PR has not even been analyzed.

@AndreiMaz Can you take a look at this PR? I believe I am correct as well as I have corrected some errors. 
https://www.w3schools.com/tags/tag_base.asp
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.usepathbaseextensions.usepathbase?view=aspnetcore-7.0

**Comment by Alerinos** [comment]
I found another error, the path of this address should be corrected. It does not include PathBase because it is built rigidly.
```
Error 404. The requested page (/scheduletask/runtask) was not found
```
https://github.com/nopSolutions/nopCommerce/blob/0e8a771ec9255c566dd5000fd6ea8a73c317fd2b/src/Libraries/Nop.Services/ScheduleTasks/ScheduleTaskRunner.cs#L149
https://github.com/nopSolutions/nopCommerce/blob/0e8a771ec9255c566dd5000fd6ea8a73c317fd2b/src/Presentation/Nop.Web.Framework/WebWorkContext.cs#L220
https://github.com/nopSolutions/nopCommerce/blob/0e8a771ec9255c566dd5000fd6ea8a73c317fd2b/src/Libraries/Nop.Services/ScheduleTasks/TaskScheduler.cs#L64

**Comment by Alerinos** [comment]
Another problem is the specification attributes.
It is probably JS, when clicked deletes the path base from the URL. 

https://gyazo.com/c60a398ee692e98526e33a1136ab0fe6

**Pull request closed without merging**
