### PR TITLE
Replaced RemoveByPattern logic to extension method

### PR DESCRIPTION
**Pull request by skoshelev**

### CODE REVIEW

**Comment by skoshelev** [comment]
Хорошо

**Comment by skoshelev** [comment]
Я все исправил

**Comment by m1dst** [comment]
This is broken!

"Collection was modified; enumeration operation may not execute."

You can't iterate through a collection and delete things from it at the same time.

**Comment by AndreiMaz** [comment]
Hi James,

Thanks a lot for reporting! Fixed

**Pull request merged**
