### PR TITLE
Fix hungarian translation of installation

### PR DESCRIPTION
**Pull request by tmsblzs**
Fixing hungarian translation in installation.hu_HU.xml

### CODE REVIEW

**Comment by tmsblzs** [comment]
I have checked the conflicts, any translation is fine.

**Comment by RomanovM** [comment]
@tmsblzs Thanks for your help. But we use [Crowdin](https://crowdin.com/project/nopcommerce) for localization. If you would like to contribute to localization, please visit our [translations page](https://www.nopcommerce.com/translations). 
If you have any complications, please let me know, and I will make your proposed changes myself.

**Comment by tmsblzs** [comment]
@RomanovM I thought the installation files are separated from crowdin translations (because no database before installing nopCommerce). I understood to use crowdin to create this file as well.
Thanks for clarification.
I will move these translations to Crowdin.

**Comment by RomanovM** [comment]
@tmsblzs Thanks. We collect such translations in Crowdin and copy them to the source before the release, see #5182 for details.

**Pull request closed without merging**
